services:
  postgres:
    image: postgres:latest
    container_name: school-erp-postgres
    environment:
      POSTGRES_DB: zw_schools_registry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: school-erp-adminer
    restart: always
    ports:
      - '8081:8080'
    depends_on:
      postgres:
        condition: service_healthy

  erp-edu-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-erp-api
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/zw_schools_registry
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_PROFILES_ACTIVE: dev
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
