spring:
  application:
    name: school-erp-api

  # ====== Main Database ======
  datasource:
    url: jdbc:postgresql://localhost:5432/zw_schools_registry
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: MainPool
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 2000
      initialization-fail-timeout: 1

  # ====== Redis Configuration ======
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 1000
          time-between-eviction-runs: 30000

  # ====== Cache Configuration ======
  cache:
    type: redis
    redis:
      time-to-live: 300000 # 5 minutes default
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "cache:"

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration/core
    baseline-on-migrate: true

# Custom cache TTLs
cache:
  tenant:
    schema-ttl: 604800000 # 7 days in ms
    access-ttl: 300000    # 5 minutes in ms

tenant:
  migration:
    locations:
      common: classpath:db/migration/tenant/common
      primary: classpath:db/migration/tenant/primary
      secondary: classpath:db/migration/tenant/secondary

multitenancy:
  platform:
    admin:
      role: platform_admin
      password: admin@erp
  header-name: X-Tenant-ID
  default-tenant: public
  auto-create-schema: true
  create-tenant-roles: true

