spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      pool-name: TestPool

  # Disable Flyway for tenant-aware operations in tests
  flyway:
    enabled: false

  # Tenant configuration for tests
  tenant:
    default-tenant: public
    auto-create-schema: false
    create-tenant-roles: false